"""init

Revision ID: 1a4a3297c625
Revises: 1fa91c5c53d7
Create Date: 2025-02-23 01:57:56.054545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models import Base


# revision identifiers, used by Alembic.
revision: str = '1a4a3297c625'
down_revision: Union[str, None] = '1fa91c5c53d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('show_id', sa.UUID(), nullable=True))
    op.drop_constraint('bookings_user_uid_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_show_uid_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'shows', ['show_id'], ['show_id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['uid'])
    op.drop_column('bookings', 'user_uid')
    op.drop_column('bookings', 'show_uid')
    op.add_column('shows', sa.Column('movie_id', sa.UUID(), nullable=True))
    op.add_column('shows', sa.Column('cinema_hall_id', sa.UUID(), nullable=True))
    op.drop_constraint('shows_movie_uid_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'cinema_halls', ['cinema_hall_id'], ['cinema_hall_id'])
    op.create_foreign_key(None, 'shows', 'movies', ['movie_id'], ['uid'])
    op.drop_column('shows', 'movie_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('movie_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_movie_uid_fkey', 'shows', 'movies', ['movie_uid'], ['uid'])
    op.drop_column('shows', 'cinema_hall_id')
    op.drop_column('shows', 'movie_id')
    op.add_column('bookings', sa.Column('show_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_show_uid_fkey', 'bookings', 'shows', ['show_uid'], ['show_id'])
    op.create_foreign_key('bookings_user_uid_fkey', 'bookings', 'users', ['user_uid'], ['uid'])
    op.drop_column('bookings', 'show_id')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
