"""init

Revision ID: 1fa91c5c53d7
Revises: 34323e8843c6
Create Date: 2025-02-22 19:53:38.400948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models import Base


# revision identifiers, used by Alembic.
revision: str = '1fa91c5c53d7'
down_revision: Union[str, None] = '34323e8843c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_uid', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('show_uid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'bookings', 'shows', ['show_uid'], ['show_id'])
    op.add_column('shows', sa.Column('movie_uid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shows', 'movies', ['movie_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'movie_uid')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'show_uid')
    op.drop_column('bookings', 'user_uid')
    # ### end Alembic commands ###
