"""init

Revision ID: 34323e8843c6
Revises: 
Create Date: 2025-02-20 12:43:50.853188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models import Base


# revision identifiers, used by Alembic.
revision: str = '34323e8843c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=False))
    op.drop_column('movies', 'realese_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('realese_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('movies', 'release_date')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    # ### end Alembic commands ###
